version: 0.0
os: linux
files:
  - source: /
    destination: /var/hello-world
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
